### ISSUE TITLE
Could not resolve all files for configuration ':app:debugRuntimeClasspath. Could not find com.huawei.hms:wearengine:5.0.1.301.

### ISSUE THREAD

**Issue by AnhVo28** [Spicy-Sparks/react-native-wear-engine#1]
BUILD FAILED in 16s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.huawei.hms:wearengine:5.0.1.301.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/huawei/hms/wearengine/5.0.1.301/wearengine-5.0.1.301.pom
       - file:/C:/Users/h84174510/.m2/repository/com/huawei/hms/wearengine/5.0.1.301/wearengine-5.0.1.301.pom
       - file:/D:/Onebox/2021/4. Side projects/8. Wearable/5. Real project/Smartum/react_native_src/node_modules/react-native/android/com/huawei/hms/wearengine/5.0.1.301/wearengine-5.0.1.301.pom
       - file:/D:/Onebox/2021/4. Side projects/8. Wearable/5. Real project/Smartum/react_native_src/node_modules/jsc-android/dist/com/huawei/hms/wearengine/5.0.1.301/wearengine-5.0.1.301.pom
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/wearengine/5.0.1.301/wearengine-5.0.1.301.pom
       - https://www.jitpack.io/com/huawei/hms/wearengine/5.0.1.301/wearengine-5.0.1.301.pom
     Required by:
         project :app > project :react-native-wear-engine

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

    at makeError (D:\Onebox\2021\4. Side projects\8. Wearable\5. Real project\Smartum\react_native_src\node_modules\execa\index.js:174:9)        
    at D:\Onebox\2021\4. Side projects\8. Wearable\5. Real project\Smartum\react_native_src\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\Onebox\2021\4. Side projects\8. Wearable\5. Real project\Smartum\react_native_src\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:106:5)
    at async Command.handleAction (D:\Onebox\2021\4. Side projects\8. Wearable\5. Real project\Smartum\react_native_src\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by AnhVo28** [comment]
I have solved this problem by adding huawei repo into gradle:

Open the build.gradle file in the android directory of your React Native project.
Go to buildscript and configure the Maven repository address and AppGallery Connect plugin for the HMS SDK.
buildscript {    
  repositories {        
    google()        
    jcenter()        
    maven { url 'https://developer.huawei.com/repo/' }   
  }    
  dependencies {        
/*          
      * <Other dependencies>        
      */
    classpath 'com.huawei.agconnect:agcp:1.4.2.301'
  }
}
Go to allprojects and configure the Maven repository address for the HMS SDK.
allprojects {
  repositories {
    /*          
     * <Other repositories>        
     */
    maven { url 'https://developer.huawei.com/repo/' }
  }
}

Reference:
https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides-V1/integrating-sdk-0000001050034173-V1

**Comment by marf** [comment]
Thank you @AnhVo28 we updated the grade file in the repository too!
